apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: guestbook
  labels:
    app: guestbook
    tier: frontend
    component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
      component: web
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
        component: web
    spec:
      containers:
      - name: frontend
        image: psrvere/k8s-sample-app:guestbook-latest
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3 