apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: guestbook
  labels:
    app: guestbook
    tier: frontend
    component: web
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
  selector:
    app: guestbook
    tier: frontend
    component: web 