apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: guestbook
  labels:
    app: guestbook
    tier: backend
    component: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: guestbook
    tier: backend
    component: redis 