apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld-app
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: helloworld-app 