# NodePort Service for Hello World Application
# This service provides external access to the application via NodePort
# Access the app at http://localhost:30080

apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-nodeport
  labels:
    app: helloworld-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: helloworld-app 