# Pod with OOM (Out of Memory) Issue
# This pod will be killed due to memory exhaustion

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-oom
  labels:
    app: nginx-web
spec:
  containers:
  - name: nginx
    image: python:alpine
    command: ["python3"]
    args: ["-c", "import time; print('Starting memory test...'); time.sleep(2); print('Allocating memory...'); a = []; [a.append('x' * 1000000) or print('Allocated chunk', len(a)) for _ in iter(int, 1)]"]
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "96Mi"  # Reduced limit to trigger OOM faster
        cpu: "100m" 