# Pod with Image Pull Error
# This pod will fail to start due to an invalid image name

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-image-error
  labels:
    app: nginx-web
spec:
  containers:
  - name: nginx
    image: nginx:invalid-tag-that-does-not-exist  # This image doesn't exist
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m" 