# Pod with Configuration Error
# This pod has invalid configuration that will cause validation errors

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-config-error
  labels:
    app: nginx-web
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    env:
    - name: NGINX_HOST
      value: "localhost"
    - name: NGINX_PORT
      value: "80"
    - name: INVALID_ENV_VAR
      value: "test"
      invalidField: "this will cause an error"  # Invalid field in env var 