# Pod with Crash Loop
# This pod will crash and restart repeatedly due to a command that exits immediately

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-crash-loop
  labels:
    app: nginx-web
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    command: ["/bin/sh"]
    args: ["-c", "echo 'Pod will crash in 5 seconds'; sleep 5; exit 1"]  # Exits with error code 1
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m" 